name: ai-agents-demo
channels:
  - conda-forge
dependencies:
  - python=3.12.11
  - pip=24.2
  - nodejs=22.9.0 # for local tooling that invokes node (not Next.js app itself)
  - pip:
      # Core agent stack
      - langgraph==0.6.7
      - openai==1.108.1
      - pydantic==2.11.9
      - langsmith==0.4.29
      - qdrant-client==1.15.1
      - mcp[cli]==1.14.1
      - letta==0.11.7
      - letta-client>=0.1.3
      - e2b-code-interpreter==2.0.0

      # Telemetry
      - opentelemetry-api>=1.30.0
      - opentelemetry-sdk>=1.30.0
      - opentelemetry-exporter-otlp>=1.30.0
      - opentelemetry-instrumentation==0.51b0
      - opentelemetry-instrumentation-fastapi==0.51b0
      - opentelemetry-semantic-conventions==0.51b0

      # Minimal API/server bits for the small full-stack app
      - fastapi==0.115.5
      - uvicorn==0.36.0
      - httpx>=0.28.1,<0.29
      - python-dotenv==1.0.1

      # Notebooks & dev
      - jupyterlab==4.4.7
      - notebook==7.4.5
      - ipykernel==6.30.1
